// <auto-generated />
namespace AgriExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedplanttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedplanttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201709221605183_added plant table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
