// <auto-generated />
namespace AgriExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddatetoblogsandcommentsandaddedtagjunctiontable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddatetoblogsandcommentsandaddedtagjunctiontable));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181443026_added date to blogs and comments and added tag junction table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
